version: "3.1"

services:
  mongo1:
    image: mongo:7.0.5-rc0
    container_name: mongo1
    restart: always
    ports:
      - 27017:27017
    command: mongod --replSet rs0 --port 27017
  mongo2:
    image: mongo:7.0.5-rc0
    container_name: mongo2
    restart: always
    ports:
      - 27018:27018
    command: mongod --replSet rs0 --port 27018
  mongo3:
    image: mongo:7.0.5-rc0
    container_name: mongo3
    restart: always
    ports:
      - 27019:27019
    command: mongod --replSet rs0 --port 27019
